### ISSUE TITLE
[SOL-57955] Allow for Solace message properties to be externally configurable

### ISSUE THREAD

**Issue by MikeR13** [SolaceProducts/solace-spring-cloud#93]
With the Solace Spring Cloud Stream Binder version 2.1.1 you had the possibility to configure a "message time to live" for all producer binding (default) or dedicated on every producer binding. 

As I have seen, this is no longer available in version 3.1.0, or did I miss something? 

It would be nice to have this feature back.

**Comment by Mrc0113** [comment]
Thanks for the tag @Nephery. I think @MikeR13 has a good point and we should consider allowing for settings like this to be configured on the binding. The reason for this would be to keep the messaging logic in the app's configuration and then your code is just functions focused on the business logic. It doesn't and shouldn't need to know how the Function is being invoked. This goes with the "write once use anywhere" mantra of Spring Cloud Function. Trigger the same functions via HTTP, Messaging, Rsocket, etc. 

@MikeR13 in the meantime this isn't available in the current version so you could do a few things: 
1. You could just use the `Message<?>` object as @Nephery suggested in your main function
2. You could use Function composition and handle adding your message properties in a separate function from the one that does your business logic
3. Another thing to consider might be allowing the consumer to decide how long they want the message to be available. This could be advantageous since some consumers might want to consume all the events no matter how old they are while others may say just throw them away after 30 seconds. You can configure this on the queue (or queue template) for each consumer. Basically tell the queue to "Respect TTL" and then you can set a "Maximum TTL (sec)" for each.

Hope that helps!

**Comment by MikeR13** [comment]
@Mrc0113 @Nephery  
"the reason for this would be to keep the messaging logic in the app's configuration and then your code is just functions focused on the business logic. It doesn't and shouldn't need to know how the Function is being invoked."
That's exactly my point.

Thanks for listing the options!

**Comment by GreenRover** [comment]
+1 Any idea what is the target release?

I would suggest following header for this feature:
- ttl
- priority 
- dmq eligible 
- cos
- http content-type (i guess this is already)

**Comment by Nephery** [comment]
@MikeR13 @GreenRover @Mrc0113 The Spring Cloud Function maintainers have implemented a way to set default Spring message headers on outbound messages: https://github.com/spring-cloud/spring-cloud-function/issues/764

So once that's released you'll be able to use SpEL to set default properties on outbound messages:
```yml
spring:
  cloud:
    function:
      definition: messageHandler
      configuration:
        messageHandler:
          output-header-mapping-expression:
            solace_applicationMessageId: "headers['solace_applicationMessageId'] ?: 'default-value'"
            solace_timeToLive: "headers['solace_timeToLive'] > 0 ? headers['solace_timeToLive'] : 5000L"
```

Or if you want to overwrite values:
```yml
spring:
  cloud:
    function:
      definition: messageHandler
      configuration:
        messageHandler:
          output-header-mapping-expression:
            solace_applicationMessageId: "'override-value'"
            solace_timeToLive: 5000L
```
