### ISSUE TITLE
Support setting client channel settings via apiProperties in spring cloud stream solace binder

### ISSUE THREAD

**Issue by jmosmg** [SolaceProducts/solace-spring-cloud#95]
SolaceJavaAutoConfigurationBase supports adding properties via the apiProperties configuration item in spring boot, e.g:

spring.cloud.solace.binders.name.environment.apiProperties

I am looking to set compressionLevel to 1, as the default of 0 is severely reducing performance to <200msg/s level.

SolaceJavaAutoConfigurationBase adds a prefix of "jcsmp." to all properties that are in apiProperties before combining them with the autowired properties (from SolaceJavaProperties),

JCSMPClientChannelProperties is built based on any pre-existing "client_channel" properties the resulting properties, but that is impossible as its based on SolaceJavaProperties and the apiProperties list (with prefixes).

Is there another way to set properties like compressionLevel?

**Comment by Nephery** [comment]
Try using `CLIENT_CHANNEL_PROPERTIES` instead of `client_channel`.

For example, to set compression level, use this as the key:
```properties
spring.cloud.stream.binders.<binder-name>.environment.solace.java.apiProperties.CLIENT_CHANNEL_PROPERTIES.compressionLevel
```

Or if you're using yaml:
```yaml
spring:
  cloud:
    stream:
      binders:
        <binder-name>:
          type: solace
          environment:
            solace:
              java:
                apiProperties:
                  CLIENT_CHANNEL_PROPERTIES:
                    compressionLevel: 1
```
